import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin", "greek"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-[#121214] text-white">{children}</body>
    </html>
  );
}
